spring:
  application:
    name: default-authorization-server
  main:
    allow-bean-definition-overriding: true
logging:
  file:
    name: logs/default-authorization-server.log
---
spring:
  profiles:
    active: development
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb    
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
server:
  port: 9000
logging:
  level:
    '[com.gusrubin.defaultauthorizationserver]': debug